### ISSUE TITLE
Création d'un back office pour gérer les droits des utilisateurs

### ISSUE THREAD

**Issue by YrenWu** [EquipeBravo/Projet-fil-rouge#11]
- Création d'un back office pour le super admin 
 Gestion des comptes utilisateurs administrateur
L'administrateur du site pourrait valider les demandes d'inscriptions, supprimer un
compte ou gérer les droits via un panneau d'administration.
- Validation d'un compte par l'administrateur
- Création manuelle d'un compte
- Nom du groupe
- Droits
- Gestion des droits par l'administrateur
- Suppression de compte par l'administrateur

**Comment by romwaldtff** [comment]
Dashboard admin terminé.
Navbar admin également mise à jour pour les différents CRUDS des entités.
