### ISSUE TITLE
Ajout de fonctionnalité : Barre de recherche sur l'ensemble du site

### ISSUE THREAD

**Issue by romwaldtff** [EquipeBravo/Projet-fil-rouge#22]
Fonctionnalité attendue dans le cachier des charges et confirmée par N. Moricet ce matin (29/03/2017).

Description : Une barre de recherche sur l'ensemble du site (partie publique) permettant aux utilisateurs d'accéder à une page de résultats correspondant à leur recherche.

**Comment by romwaldtff** [comment]
Fonctionnel pour l'affichage des évènements depuis le commit 0635a6f6791ae560a8f590bd5497b726a1b79513 ( Mar 29, 2017 )

**Comment by YrenWu** [comment]
Cool beau boulot Romu \o/ !!!

**Comment by romwaldtff** [comment]
Fonctionnel à 100% depuis le commit c5360811a386247dd948f8b684dd24560f955fda ( Mar 30, 2017 )
