### ISSUE TITLE
Ajout de l'annuaire des correspondants (Fonctionnalité 4)

### ISSUE THREAD

**Issue by MorganDL-17** [EquipeBravo/Projet-fil-rouge#26]
Fonctionnalité 4 : Annuaire des correspondants (équipes, administratifs, etc…).

**Comment by romwaldtff** [comment]
Fonctionnel depuis le commit f44cf819d600f267f1a4f1ef72e7a540d4c87d75 ( Apr 3, 2017 )

Exemple de fonctionnement : 
Ajouter une nouvelle "Description du club" (qui sera donc une nouvelle entrée dans la page "A Propos"

Titre : "ANNUAIRE DES CORRESPONDANTS"

Contenu : M. Bertrand C. 02 40 76 59 36 bertrand.c@asptt-handball.fr
Mme Roger F. 02 40 76 59 37 roger.f@asptt-handball.fr

À chaque "entrée"/retour à la ligne, le retour à la ligne du contenu s'affichera correctement, permettant d'afficher une liste de correspondants.
