### ISSUE TITLE
Intéger un formulaire d'upload de fichier 

### ISSUE THREAD

**Issue by YrenWu** [EquipeBravo/Projet-fil-rouge#8]
Intéger un formulaire d'upload de fichier  dans /gallery/file/new : 

- mettre au point une vérification du type mime pour autoriser ou non l'upload
- créer une gallerie ou voir les photos uploadées si possible classées par équipes

**Comment by YrenWu** [comment]
avec une belle petite gallerie (si possible liée à l'équipe)

**Comment by VincentCana** [comment]
ok
